version = 5.6.0
archive_dir = /etc/letsencrypt/archive/vuongdovu.com
cert = /etc/letsencrypt/live/vuongdovu.com/cert.pem
privkey = /etc/letsencrypt/live/vuongdovu.com/privkey.pem
chain = /etc/letsencrypt/live/vuongdovu.com/chain.pem
fullchain = /etc/letsencrypt/live/vuongdovu.com/fullchain.pem
[renewalparams]
account = 16c53582449e43acf0d71a92f77435e2
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
vuongdovu.com = /var/www/certbot
www.vuongdovu.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-05-16T12:12:28
